version: 2
updates:
  # Maintain dependencies for the whole project (Gradle)
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    # Custom labels for PRs
    labels:
      - "dependencies"
      - "security"
    # Strategy to handle versioning
    versioning-strategy: increase

  # Maintain GitHub Actions versions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "ci-cd"
